source 'https://rubygems.org'
gem 'rails', '3.2.8'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem "thin", ">= 1.4.1"
gem "mongoid", ">= 3.0.3"
gem 'kaminari'
gem "haml", ">= 3.1.7"
gem "haml-rails", ">= 0.3.4", :group => :development
gem "hpricot", ">= 0.8.6", :group => :development
gem "ruby_parser", ">= 2.3.1", :group => :development
gem "factory_girl_rails", ">= 4.0.0", :group => [:development, :test]
gem "bootstrap-sass", ">= 2.0.4.0"
gem "omniauth", ">= 1.1.0"
gem "omniauth-twitter"
gem "simple_form"
gem 'rMeetup','1.0', :git=>'git://github.com/prwteas/rmeetup.git'
gem 'pry-rails'
gem 'curb'
gem 'resque'
gem 'foreman'
gem 'batch_factory'
gem 'linkedin'
gem 'tabler'
gem 'twitter'
gem 'tweetstream'
