source 'https://rubygems.org'
gem 'rails', '3.2.3'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem "haml", ">= 3.1.6"
gem "haml-rails", ">= 0.3.4", :group => :development
gem 'hpricot'
gem "bson_ext", ">= 1.6.4"
gem "mongoid", ">= 2.4.11"
gem "omniauth", ">= 1.1.0"
gem "omniauth-twitter"
gem "zurb-foundation"
gem "will_paginate_mongoid"
gem "therubyracer", :group => :assets, :platform => :ruby
gem 'pry-rails', :group => [:development,:test]
gem 'batch_factory', :git => 'git://github.com/jumph4x/batch-factory.git'
gem 'rMeetup','1.0', :git=>'git://github.com/prwteas/rmeetup.git'
gem 'mongoid-mapreduce'
gem 'tabler'
gem 'resque'
gem 'foreman'
gem 'thin'
gem 'curb'